import assert from "node:assert/strict";

// An assert.ok(false) in a nested function with a ton of text (either code or comments) gets really slow.
// The more nested the function is, the slower it is.
// It doesn't happen with assert.equal(true, false), nor assert.ok(false, "message")

function f1() {
  function f2() {
    function f3() {
      function f4() {
        function f5() {
          function f6() {
            function f7() {
              function f8() {
                function f9() {
                  function f10() {
                    function f11() {
                      function f12() {
                        function f13() {
                          function f14() {
                            function f15() {
                              function f16() {
                                function f17() {
                                  function f18() {
                                    // Tons of commented out lines
                                    //
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A
                                    // A

                                    assert.ok(false);
                                  }
                                  f18();
                                }
                                f17();
                              }
                              f16();
                            }
                            f15();
                          }
                          f14();
                        }
                        f13();
                      }
                      f12();
                    }
                    f11();
                  }
                  f10();
                }
                f9();
              }
              f8();
            }
            f7();
          }
          f6();
        }
        f5();
      }
      f4();
    }
    f3();
  }
  f2();
}
f1();
